# Generated by Django 3.2.25 on 2024-09-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0003_globalsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicissuequestion',
            name='var_rating',
            field=models.FloatField(),
        ),
    ]
